---
- hosts: all

  tasks:
    - name: install dvc-2.9.3 .deb source
      apt:
        deb: https://dvc.org/download/linux-deb/dvc-2.9.3
        state: present
      become: true
      register: apt_output
      when: ansible_os_family == 'Debian'

    - name: install dvc-2.9.3 .rpm source
      yum:
        name: https://dvc.org/download/linux-rpm/dvc-2.9.3
        state: present
      become: true
      when: ansible_os_family == 'RedHat'
