---
- hosts: all

  tasks:
    - name: example repo folder
      stat:
        path: ~/example-get-started
      register: example_repo

    - name: check if working
      shell: |
        cd ~/example-get-started
        dvc doctor
        dvc status
        dvc metrics show
      args:
        executable: /bin/bash
      when: example_repo.stat.exists
